SeatYourself/config/routes.rb
SeatYourself::Application.routes.draw do

  get 'restaurants/view/:cuisine' => 'restaurants#index'

  get 'reservations' => 'reservations#show'

  resources :restaurants do
    resources :reservations, only: [:new, :create, :destroy, :edit, :update]
    resources :reviews, only: [:new, :create, :destroy]
  end

  root "restaurants#index"

  resources :users, only: [:new,:create,:destroy,:show]

  resources :sessions, only: [:new,:create,:destroy]

end

SeatYourself/app/views/shared/_header.html.erb
<div class="header">

  <div class="logo">
    <h1>SeatYourself</h1>
  </div>

  <div class="nav">

    <ul>
      <li><%= link_to "Find a Restaurant", restaurants_path %></li>
      <% @user = session[:user_id].nil? ? "login" : session[:user_id] %>
      <% if @user == 'login' %>
      <li><%= link_to "Manage Reservations", new_session_path %></li>
      <% elsif User.find_by(id:@user).user_type == "diner" %>
      <li><%= link_to "Manage Reservations", user_path(@user) %></li>
      <% else %>
      <li><%= link_to "Manage Restaurants", user_path(@user) %></li>
      <% end %>
    </ul>

  </div>

  <div class="login">
    <ul>
      <% if authenticated? %>
      <li>Welcome back <%= current_user.first_name %>!</li>
      <li><%= link_to "Log Out", session_path(current_user.id), method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", new_session_path %></li>
      <li><%= link_to "Register a New Account", new_user_path %></li>
      <% end %>
      <li>
        <%= form_tag "/search" do %>
          <%= text_field_tag :search, nil, placeholder: "Enter search term..." %>
          <%= submit_tag "Search" %>

        <% end %>

      </li>
    </ul>
  </div>

</div>

<div id="header_alt">

</div>

SeatYourself/app/views/shared/_reservation_form.html.erb
<% if authenticated? %>
  <%= form_for [@restaurant, @reservation] do |f| %>
    <div class="reservation_form_container">
    
      <div>
        <%= select_tag "start_date",  options_for_select(@dates_array) %>
        <%= f.select(:start_time, @times_array) %>
      </div>
      <div style="text-align: right;">
        <%= f.label :seats, "Number of seats:" %><%= f.select(:seats, [ ["1 seat",1], ["2 seats",2], ["3 seats",3], ["4 seats",4], ["5 seats",5], ["6 seats",6], ]) %>
      </div>

    
    </div>
    <div class="reservation_form_submit">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <div class="not_allowed_reserve">
    <h4>Please log in first!</h4> 
    <p>You need an account to make a reservation.
  </div>
<% end %>