Crowdfunder/config/routes.rb
Crowdfunder::Application.routes.draw do
  root "projects#index"
  resources :projects do
    resources :pledges, only: [ :new, :create ]
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

Crowdfunder/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

Crowdfunder/app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :tier

  validates :amount, :numericality => true
end

Crowdfunder/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tiers
	has_many :users, :through => :tiers
	has_many :pledges
	mount_uploader :image, ImageUploader
	accepts_nested_attributes_for :tiers
end

Crowdfunder/app/models/tier.rb
class Tier < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
	has_many :pledges
end

Crowdfunder/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :tiers
  has_many :projects, :through => :tiers
  has_many :pledges

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

end

Crowdfunder/app/controllers/breakpoints_controller.rb
class BreakpointsController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		@tier = @project.tiers.new(tier_params)

		if @tier.save
			redirect_to @project
		else
			# empty for now
		end
	end

end

Crowdfunder/app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @pledge = @project.pledges.new

  end

  def create

    @project = Project.find(params[:project_id])
    params[:pledge][:project_id] = params[:project_id]
    
    @user = current_user
    @tier = Tier.find(params[:pledge][:tier_id])
    

    @pledge = @user.pledges.new(pledge_params)
    if @pledge.save
      if @project.funded
        funded = @project.funded + @pledge.amount
      else
        funded = @pledge.amount
      end
      @project.update_column(:funded, funded) 

      @tier_backed = @tier.pledges.inject(0) {|sum, pledge| sum + pledge.amount}

      @new_values = {
        msgHeader: "Pledge Confirmed!",
        msg: "Thank you! You have successfully backed this project.",
        tierID: params[:pledge][:tier_id],
        funded: funded,
        tierSum: @tier_backed,
        backers: @tier.pledges.count
      }

    else
      @new_values = { msg: "Failure! Oh" }
    end

    respond_to do |format|
      format.html {  }
      format.json { 
        render :json => @new_values

      }
      format.js {  }
    end


  end


  private

  def pledge_params
    params.require(:pledge).permit(:amount, :tier_id, :user_id, :project_id)
  end
end

Crowdfunder/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.page(params[:page])

    respond_to do |format|
      format.js 
      format.html
    end

    @projects.each do |x|
      if x.finish_date == Date.today
        #x.destroy
      end 
    end 
  end

  def new
    @project = Project.new
    #@project.image = params[:file]
  end

  def show
    @project = Project.find(params[:id])
    @days_remaining = (@project.finish_date - @project.start_date).to_i
    @pledge = @project.pledges.new

  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id if current_user
    if @project.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to root_path
    else
      render 'edit'
    end 
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  def project_params
    params.require(:project).permit(:name, :description, :start_date, :finish_date, :funding_goal, :image, tiers_attributes: [:id, :amount, :tier_description])
  end
end

Crowdfunder/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to projects_path, notice: "Logged in!"
    else
      render :new, alert: "Email or password was invalid." 
    end
  end
  def destroy
    logout
    redirect_to root_url
  end

  private
  def session_params
    params.require(:session).permit(:email, :password, :remember_me)
  end
end

Crowdfunder/app/controllers/tiers_controller.rb
class BreakpointsController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		@tier = @project.tiers.new(tier_params)

		if @tier.save
			redirect_to @project
		else
			# empty for now
		end
	end

end

Crowdfunder/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to projects_path, notice: "Signed up!"
    else
      render :new
    end
  end

  def show 
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end 
end

Crowdfunder/app/helpers/breakpoints_helper.rb
module BreakpointsHelper
end

Crowdfunder/app/helpers/pledges_helper.rb
module PledgesHelper
end

Crowdfunder/app/views/pledges/new.html.erb
<h1>Enter your pledge amount:</h1>

<%= form_for [@project, @pledge] do |f| %>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>

  <h4>Select Reward:</h4>
  <ul>
    <% @project.tiers.each do |tier| %>
      <li>
        <label><%= f.radio_button(:tier_id, tier.id) %><strong><%= tier.amount %></strong> | <%= tier.tier_description %></label>
      </li>

    <% end %>
  </ul>

  <div class="action">
    <%= f.submit %>
  </div>  
  
<% end %>

Crowdfunder/app/views/projects/_project.html.erb
  <div class="projects_listed large-4 columns">
    <strong><%= project.name %></strong><br>
    Description: <%= project.description %><br>
    id: <%= project.id %><br>
    <%= link_to 'Show', project_path(project.id) %>
    <br>
  </div>

Crowdfunder/app/views/projects/_tiers.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :amount %>
    <br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :tier_description %>
    <br>
    <%= f.text_field :tier_description %>
  </div>
  <%= link_to_remove_association "remove tier", f %>
</div>

Crowdfunder/app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= @project.name %><br>
<%= @project.start_date %><br>
<%= @project.finish_date %><br>
<%= @project.funding_goal %><br>

<%= form_for(@project ) do |f|%>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</div>
	<label>Project Image</label>
    <%= f.file_field :image %>
	<h4>Add Tiers:</h4>
	<div id="tiers">
    <%= f.fields_for :tiers do |tier| %>
      <%= render 'tiers', :f => tier %>
    <% end %>
    <div class="links">
	    <%= link_to_add_association 'add tier', f, :tiers, :partial => "tiers" %>
	  </div>
	</div>
	<div class="action">
		<%= f.submit %>
	</div>
<% end %>

Crowdfunder/app/views/projects/index.html.erb
<div class='project_index'>
	<h1>Projects#index</h1>
	<p>Find me in app/views/projects/index.html.erb</p>
	<%= link_to 'New', new_project_path %><br><br>
</div>

<<<<<<< HEAD

	<% @projects.each do |x| %>
<div class="row">
	<div class="projects_listed large-4 columns">
		<strong><%= x.name %></strong><br>
		Description: <%= x.description %><br>
		id: <%= x.id %><br>
		<%= image_tag x.image.thumb.url %><br>
		<%= link_to 'Show', project_path(x.id) %>

<div class="row" id="projects">


	<%= render @projects %>
	<div style="margin-top: 50px;">
		<%= paginate @projects %>

	</div>


</div>

Crowdfunder/app/views/projects/index.js.erb
$('#projects').append('<%= j render(@projects) %>');
$('.pagination').replaceWith('<%= j paginate(@projects) %>');

Crowdfunder/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for(@project) do |f|%>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :start_date %><br />
		<%= f.date_select :start_date %>
	</div>
	<div class="field">
		<%= f.label :finish_date %><br />
		<%= f.date_select :finish_date %>
	</div>
	<div class="field">
		<%= f.label :funding_goal %><br />
		<%= f.text_field :funding_goal %>
	</div>
	<label>Project Image</label>
    <%= f.file_field :image %>
	
	<h4>Add Tiers:</h4>
	<div id="tiers">
    <%= f.fields_for :tiers do |tier| %>
      <%= render 'tiers', :f => tier %>
    <% end %>
    <div class="links">
	    <%= link_to_add_association 'add tier', f, :tiers, :partial => "tiers" %>
	  </div>
	</div>

	<div class="action">
		<%= f.submit %>
	</div>
<% end %>

Crowdfunder/app/views/projects/show.html.erb
	<div id="pledge_confirmation">
		<h2></h2>
		<p></p>
	</div>

	<div class='row'>
		<table class="project_details large-6 columns">
			<h1><%= @project.name %></h1>		
			<tr><td>Start date:</td><td> <%= @project.start_date %></td></tr>
			<tr><td>End date: </td><td><%= @project.finish_date %></td></tr>
			<tr><td>Days remaining: </td><td><%= @days_remaining %></td></tr>	
		</table>
		<div class="project_funding large-6 columns">

			<strong>Total money raised:</strong> $<%= @project.funded %><br><br>
			<strong>Funding goal:</strong> $<%= @project.funding_goal %>

			<span id="project_funded_amount"><%= @project.funded %></span>

		</div>
	</div>
</div>
<div class="inner_project_page"><br>
	<% if flash[:alert] %>
	<div class="alert" style="color: red; font-size: 3em;"><%= flash[:alert] %></div>
	<% end %>
	<div class="project_text_description">
		<%= @project.description %>
		<% if current_user %>
		<% current_user.pledges.each do |p| %>
		<% if p.project.id == @project.id %><br>
		<%= "You've already backed this project." %>
		<% break %>
		<% end %>
		<% end %>
		<% end %>


		<div class="pledge_form" style="text-align: left; margin-top: 50px; display: none;">
			
			<%= form_for [@project, @pledge] do |f| %>
			<h2>Make a Pledge</h2>
			<div class="field">
				<%= f.label :amount %><br>
				<%= f.text_field :amount %>
				<%= f.hidden_field :tier_id %>
			</div>
			<h4>Selected Reward: <span id="selected_reward"></span></h4>
			<div class="action">
				<%= f.submit %>
			</div>  
			<% end %>
		</div>
	</div>


	<div class="project_reward_tiers">
		<% @project.tiers.each do |b| %>

		<br><br><div class="project_reward_tier" id="tier_<%= b.id %>">
			Pledge $<span class="tier_amount"><%= b.amount %></span> or more<br><br>
			Backers: <%= b.pledges.count %><br><br>

			Sum: <%= @tier_total_money_backed = b.pledges.inject(0) {|sum, pledge| sum + pledge.amount} %><br><br>
			<span class="tier_description"><strong>Reward:</strong> <%= b.tier_description %></span><br><br>

		<div class="project_reward_tier" id="tier_<%= b.id %>">
			Pledge $<span class="tier_amount"><%= b.amount %></span> or more<br>
			Backers: <span class="tier_backers"><%= b.pledges.count %></span><br>

			Sum: <span class="tier_sum"><%=  @tier_total_money_backed = b.pledges.inject(0) {|sum, pledge| sum + pledge.amount} %></span><br>
			<span class="tier_description"><%= b.tier_description %></span>

			
		</div>
		<% end %>			
	</div>
	<%= render 'layouts/editdestroyproject' %>
	<%= link_to "< Return home", projects_path, class: 'return_home' %>
	<script>
	</script>